name: "Setup Docker on macOS"
description: "Setup Docker on macOS using Colima, Lima-VM, and Homebrew."
inputs:
  upgrade-qemu:
    description: "Upgrade QEMU to the latest version. Add a lot of time to the job."
    required: false
    default: "false"
  lima:
    description: "Lima version. Defaults to the latest version."
    required: false
    default: "latest"
  colima:
    description: "Colima version. Defaults to the latest version."
    required: false
    default: "latest"
  colima-network-address:
    description: "Starts Colima with a reachable network address (`--network-address`). Makes Colima startup slower."
    required: false
    default: "false"
outputs:
  colima-version:
    value: ${{ steps.colima-version.outputs.version }}
    description: Version of Colima
  docker-client-version:
    value: ${{ steps.docker-client-version.outputs.version }}
    description: Version of the Docker client
  docker-compose-version:
    value: ${{ steps.docker-compose-version.outputs.version }}
    description: Version of Docker Compose
runs:
  using: "composite"
  steps:
    - name: OS safety check
      if: runner.os != 'macOS'
      run: |
        echo "Not a macOS runner, exiting."
        exit 1
      shell: bash
    - name: ARM64 safety check
      run: |
        arch_name=$(uname -m)
        if [ "$arch_name" = "arm64" ]
        then
            echo "Detected M-series processor runner without nested virtualization support, exiting."
            exit 1
        else
            echo "Running on supported architecture: ${arch_name}"
        fi
      shell: bash
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - name: Check nix channel
      run: |
        nix-channel --list
        nix-channel --update
      shell: bash
    - name: Install Colima
      run: |
        echo "::group::Installing Colima"
        nix-env -iA nixos.colima
        echo "::endgroup::"
      shell: bash
    - name: Configure Docker Compose plugin
      run: |
        mkdir -p ~/.docker/cli-plugins
        ln -sfn "$(brew --prefix)/opt/docker-compose/bin/docker-compose" ~/.docker/cli-plugins/docker-compose
      shell: bash
    - name: Start Colima
      env:
        COLIMA_NETWORK_ADDRESS: ${{ inputs.colima-network-address }}
      run: |
        CPU_COUNT=$(sysctl -n hw.ncpu)
        MEMORY=$(sysctl hw.memsize | awk '{print $2/1024/1024/1024}')
        COLIMA_ARGS="--cpu $CPU_COUNT --memory $MEMORY"
        if [ $COLIMA_NETWORK_ADDRESS == "true" ]
        then
          COLIMA_ARGS="$COLIMA_ARGS --network-address"
        fi
        echo "::group::Starting Colima with args: $COLIMA_ARGS"
        colima start $COLIMA_ARGS
        echo "::endgroup::"
      shell: bash
    - id: docker-client-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: docker-compose-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker compose version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: colima-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        colima version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
