name: "Setup Docker on macOS"
description: "Setup Docker on macOS using Colima, Lima-VM, and Homebrew."
outputs:
  colima-version:
    value: ${{ steps.colima-version.outputs.version }}
    description: Version of Colima
  docker-client-version:
    value: ${{ steps.docker-client-version.outputs.version }}
    description: Version of the Docker client
  docker-compose-version:
    value: ${{ steps.docker-compose-version.outputs.version }}
    description: Version of Docker Compose
runs:
  using: "composite"
  steps:
    - name: Safety check
      if: runner.os != 'macOS'
      run: |
        echo "Not a macOS runner, exiting."
        exit 1
      shell: bash
    - name: "Cache Nix store"
      uses: actions/cache@v3.0.8
      id: nix-cache
      with:
        path: /tmp/nixcache
        key: ${{ runner.os }}-nix-cache
    - name: "Install Nix"
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - name: "Import Nix store cache"
      if: steps.nix-cache.outputs.cache-hit == 'true'
      run: |
        nix-store --import < /tmp/nixcache
      shell: bash
    - name: Install Colima with nix
      run: nix-env -iA colima
      shell: bash
    - name: Install Docker with nix
      run: nix-env -iA docker
      shell: bash
    - name: Start Colima
      run: colima start
      shell: bash
    - name: Set Docker client version output
      id: docker-client-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Set Docker Compose version output
      id: docker-compose-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker compose version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Set Colima version output
      id: colima-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        colima version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: "Export Nix store cache"
      if: steps.nix-cache.outputs.cache-hit == 'false'
      run: |
        mkdir -p /tmp/nixcache
        nix-store --export > /tmp/nixcache
      shell: bash
