name: "Setup Docker on macOS"
description: "Setup Docker on macOS using Colima, Lima-VM, and Homebrew."
outputs:
  colima-version:
    value: ${{ steps.colima-version.outputs.version }}
    description: Version of Colima
  docker-client-version:
    value: ${{ steps.docker-client-version.outputs.version }}
    description: Version of the Docker client
  docker-compose-version:
    value: ${{ steps.docker-compose-version.outputs.version }}
    description: Version of Docker Compose
runs:
  using: "composite"
  steps:
    - name: Safety check
      if: runner.os != 'macOS'
      run: |
        echo "Not a macOS runner, exiting."
        exit 1
      shell: bash
    - name: Update Homebrew
      run: |
        brew update --preinstall
        brew_repository="$(brew --repository)"
        mkdir -p .github
        cd .github
        cat "$(brew edit --print-path --formula colima)" > brew-colima
        cat "$(brew edit --print-path --formula lima)" > brew-lima
        cat "$(brew edit --print-path --formula docker )" > brew-docker
        cat "$(brew edit --print-path --formula docker-compose)" > brew-docker-compose
      shell: bash
    - name: Pre-cache
      run: echo "BREW_CELLAR=$(brew --cellar)" >> $GITHUB_ENV
      shell: bash
    - name: Configure Homebrew cache
      id: homebrew-cache
      uses: actions/cache@v3.3.1
      with:
        path: |
          ${{ env.BREW_CELLAR }}/colima
          ${{ env.BREW_CELLAR }}/lima
          ${{ env.BREW_CELLAR }}/docker
          ${{ env.BREW_CELLAR }}/docker-compose
        key: brew-${{ hashFiles('.github/brew-*') }}
        restore-keys: brew-${{ hashFiles('.github/brew-*') }}
    - name: Install packages that depends on Colima restored from cache
      if: ${{ steps.homebrew-cache.outputs.cache-hit == 'true' }}
      run: brew install --only-dependencies colima
      shell: bash
    - name: Relink Docker client, Docker Compose, and Colima
      if: ${{ steps.homebrew-cache.outputs.cache-hit == 'true' }}
      run: |
        brew unlink docker docker-compose colima lima
        brew link docker docker-compose colima lima
      shell: bash
    - name: Install Docker client, Docker Compose, and Colima.
      if: ${{ steps.homebrew-cache.outputs.cache-hit != 'true' }}
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
      run: brew install docker docker-compose colima lima
      shell: bash
    - name: Manually reinstall QEMU due to bug in GH actions (see https://github.com/actions/runner-images/issues/8104)
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: "1"
      run: |
        brew remove --ignore-dependencies qemu
        cd /tmp
        curl -o ./qemu.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/dc0669eca9479e9eeb495397ba3a7480aaa45c2e/Formula/qemu.rb
        brew install --formula ./qemu.rb
      shell: bash
    - name: Configure Docker Compose plugin
      run: |
        mkdir -p ~/.docker/cli-plugins
        ln -sfn "$(brew --prefix)/opt/docker-compose/bin/docker-compose" ~/.docker/cli-plugins/docker-compose
      shell: bash
    - name: Start Colima
      run: colima start
      shell: bash
    - id: docker-client-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: docker-compose-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker compose version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: colima-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        colima version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
